export enum ExceptionCode {
  // Common Error
  INVALID_INPUT = 400,
  FORBIDDEN = 403,
  API_NOT_FOUND = 404,
  UNKNOWN_SERVER_ERROR = 500,

  // Auth Error
  AUTHORIZATION_FAILED = 1000,
  INVALID_ACCESS_TOKEN = 1001,
  INVALID_REFRESH_TOKEN = 1002,

  // User Error
  NOT_FOUND_USER = 2000,
  DUPLICATED_USERNAME = 2001,
  INSUFFICIENT_AUTHORITY = 2002,

  // Product Error
  NOT_FOUND_PRODUCT = 3000,
}
